version: "3.9"
services:
  redis:
    image: "redislabs/redis-stack:edge"
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - ./data:/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure